FROM python:2.7

RUN apt-get clean && apt-get update && apt-get install -y \
		gcc \
		gettext \
		mysql-client libmysqlclient-dev \
		postgresql-client libpq-dev \
		sqlite3 \
		libgeos-dev libproj-dev gdal-bin libjpeg-dev \
		supervisor \
	--no-install-recommends && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN pip install --no-cache-dir -r requirements.txt
# QUICK FIX
RUN pip install -e "git+https://bitbucket.org/opendream/podd-form-generator#egg=podd_form_generator"

RUN pip install uwsgi
RUN mkdir -p /usr/config/
COPY docker-config/uwsgi.ini /usr/config/
COPY docker-config/supervisor-app.conf /etc/supervisor/conf.d/

VOLUME /usr/src/app
EXPOSE 9001

CMD ["supervisord", "-n"]
