# -*- encoding: utf-8 -*-

from django.utils.translation import ugettext_lazy as _


GROUP_WORKING_TYPE_ADMINSTRATION_AREA = 1
GROUP_WORKING_TYPE_REPORT_TYPE = 2
GROUP_WORKING_TYPE_ALERT_REPORT_ADMINSTRATION_AREA = 3
GROUP_WORKING_TYPE_ALERT_CASE_ADMINSTRATION_AREA = 4
GROUP_WORKING_TYPE_ALERT_REPORT_REPORT_TYPE = 5
GROUP_WORKING_TYPE_ALERT_CASE_REPORT_TYPE = 6

GROUP_WORKING_TYPE_CHOICES = (
    (0, ''),
    (GROUP_WORKING_TYPE_ADMINSTRATION_AREA, 'Administration Area'),
    (GROUP_WORKING_TYPE_REPORT_TYPE, 'Report Type'),
    (GROUP_WORKING_TYPE_ALERT_REPORT_ADMINSTRATION_AREA, 'Alert New Report on Administration Area'),
    (GROUP_WORKING_TYPE_ALERT_CASE_ADMINSTRATION_AREA, 'Alert New Case on Administration Area'),
    (GROUP_WORKING_TYPE_ALERT_REPORT_REPORT_TYPE, 'Alert New Report on Report Type'),
    (GROUP_WORKING_TYPE_ALERT_CASE_REPORT_TYPE, 'Alert New Case on Report Type'),
)


GROUP_ROLE_REPORTER = 1
GROUP_ROLE_PROSPECTOR = 2

GROUP_ROLE_CHOICES = (
    (GROUP_ROLE_REPORTER, 'Reporter'),
    (GROUP_ROLE_PROSPECTOR, 'Prospector'),
)


USER_STATUS_VOLUNTEER = 'VOLUNTEER'
USER_STATUS_ADDITION_VOLUNTEER = 'ADDITION_VOLUNTEER'
USER_STATUS_COORDINATOR = 'COORDINATOR'
USER_STATUS_PODD = 'PODD'
USER_STATUS_LIVESTOCK = 'LIVESTOCK'
USER_STATUS_PUBLIC_HEALTH = 'PUBLIC_HEALTH'

USER_STATUS_CHOICES = (
    ('', ''),
    (USER_STATUS_VOLUNTEER, u'อาสาสมัครโครงการ'),
    (USER_STATUS_ADDITION_VOLUNTEER, u'อาสาสมัครเพิ่มเติม'),
    (USER_STATUS_COORDINATOR, u'ผู้ประสานงาน'),
    (USER_STATUS_PODD, u'ทีมวิจัย'),
    (USER_STATUS_LIVESTOCK, u'ปศุสัตว์'),
    (USER_STATUS_PUBLIC_HEALTH, u'สาธารณสุข'),
)

PRIORITY_NONE = 0
PRIORITY_IGNORE = 1 #!!!
PRIORITY_OK = 2
PRIORITY_CONTACT = 3
PRIORITY_FOLLOW = 4 #!!!
PRIORITY_CASE = 5

PRIORITY_CHOICES = (
    (PRIORITY_NONE, 'None'),
    (PRIORITY_IGNORE, 'Ignore'),
    (PRIORITY_OK, 'OK'),
    (PRIORITY_CONTACT, 'Contact'),
    (PRIORITY_FOLLOW, 'Follow'),
    (PRIORITY_CASE, 'Case'),
)

PARENT_TYPE_GENERAL = 'GENERAL'
PARENT_TYPE_MERGE = 'MERGE'
PARENT_TYPE_DODD = 'DODD'
PARENT_TYPE_CHOICES = (
    (PARENT_TYPE_GENERAL, 'General'),
    (PARENT_TYPE_MERGE, 'Merge'),
    (PARENT_TYPE_DODD, 'DODD')
)


NEWS_TYPE_NEWS = 'NEWS'
NEWS_TYPE_UPDATED_REPORT_TYPE = 'UPDATED_REPORT_TYPE'
NEWS_TYPE_ADMINISTRATION_AREA = 'AREA'
NEWS_TYPE_SUBSCRIBE_AUTHORITY = 'SUBSCRIBE_AUTHORITY'

SUPPORT_LIKE_ME_TOO = 'SUPPORT_LIKE_ME_TOO'
SUPPORT_LIKE_COMMENT = 'SUPPORT_LIKE_COMMENT'
SUPPORT_ME_TOO_COMMENT = 'SUPPORT_ME_TOO_COMMENT'
SUPPORT_LIKE_ME_TOO_COMMENT = 'SUPPORT_LIKE_ME_TOO_COMMENT'
SUPPORT_LIKE = 'SUPPORT_LIKE'
SUPPORT_ME_TOO = 'SUPPORT_ME_TOO'
SUPPORT_COMMENT = 'SUPPORT_COMMENT'


# TODO: fixed on node.server add more news type choices push to gcm too, #GCM below
NewsTypeChoices = (
    (NEWS_TYPE_NEWS, 'News'), # GCM
    (NEWS_TYPE_UPDATED_REPORT_TYPE, 'Update report type'),
    (NEWS_TYPE_ADMINISTRATION_AREA, 'Area'), # GCM
    (NEWS_TYPE_SUBSCRIBE_AUTHORITY, 'Subscribe'), # GCM

    (SUPPORT_LIKE_ME_TOO, 'Support: like and me too'),
    (SUPPORT_LIKE_COMMENT, 'Support: like and comment'),
    (SUPPORT_ME_TOO_COMMENT, 'Support: me too and comment'),
    (SUPPORT_LIKE_ME_TOO_COMMENT, 'Support: like, me too and comment'),
    (SUPPORT_LIKE, 'Support: like'),
    (SUPPORT_ME_TOO, 'Support: me too'),
    (SUPPORT_COMMENT, 'Support: comment'),

)

NOTIFICATION_SUPPORT_TEMPLATES = {
    SUPPORT_LIKE_ME_TOO_COMMENT: u'ให้กำลังใจ ประสบด้วย และ แสดงความคิดเห็น',
    SUPPORT_LIKE_ME_TOO: u'ให้กำลังใจ และ ประสบด้วย',
    SUPPORT_LIKE_COMMENT: u'ให้กำลังใจ และ แสดงความคิดเห็น',
    SUPPORT_ME_TOO_COMMENT: u'ประสบด้วย และ แสดงความคิดเห็น',
    SUPPORT_LIKE: u'ให้กำลังใจ',
    SUPPORT_ME_TOO: u'ประสบด้วย',
    SUPPORT_COMMENT: u'แสดงความคิดเห็น'
}
NOTIFICATION_SUPPORT_TEMPLATE_PREFIX = u'{{ created_by.name }}'
NOTIFICATION_SUPPORT_TEMPLATE_SUFFIX = u'กับรายงาน {{ report.type.name }} ของคุณ'


STATUS_PUBLISH = 1
STATUS_DELETE = -1

STATUS_CHOICES = (
    (STATUS_PUBLISH, 'Publish'),
    (STATUS_DELETE, 'Delete')
)


INVESTIGATION_TYPE_FARM = 1
INVESTIGATION_TYPE_SUMMARY = 2

INVESTIGATION_TYPE = (
    (INVESTIGATION_TYPE_FARM, 'Investigation: farm'),
    (INVESTIGATION_TYPE_SUMMARY, 'Investigation: summary')
)